const rimeGroups = Object.freeze({
    a: "a",
    i: "i",
    u: "u",
    e: "e",
    o: "o",
    n: "n",
    hi: "hi",
    ha: "ha",
    hu: "hu",
    ho: "ho",
    su: "su",
    ya: "ya",
    yu: "yu",
    yo: "yo",
});

const onsetGroups = Object.freeze({
    vowels: 1,
    k: 2,
    s: 3,
    t: 4,
    n: 5,
    h: 6,
    m: 7,
    y: 8,
    r: 9,
    w: 10,
    g: 11,
    z: 12,
    d: 13,
    b: 14,
    p: 15,
    j: 16,
    c: 17,
});

export const hiragana = Object.freeze([
    {
        id: 1,
        term: "あ",
        definition: "a",
        rimeGroup: rimeGroups.a,
        onsetGroups: onsetGroups.vowels,
    },
    {
        id: 2,
        term: "い",
        definition: "i",
        rimeGroup: rimeGroups.i,
        onsetGroups: onsetGroups.vowels,
    },
    {
        id: 3,
        term: "う",
        definition: "u",
        rimeGroup: rimeGroups.u,
        onsetGroups: onsetGroups.vowels,
    },
    {
        id: 4,
        term: "え",
        definition: "e",
        rimeGroup: rimeGroups.e,
        onsetGroups: onsetGroups.vowels,
    },
    {
        id: 5,
        term: "お",
        definition: "o",
        rimeGroup: rimeGroups.o,
        onsetGroups: onsetGroups.vowels,
    },
    {
        id: 6,
        term: "か",
        definition: "ka",
        rimeGroup: rimeGroups.a,
        onsetGroups: onsetGroups.k,
    },
    {
        id: 7,
        term: "き",
        definition: "ki",
        rimeGroup: rimeGroups.i,
        onsetGroups: onsetGroups.k,
    },
    {
        id: 8,
        term: "く",
        definition: "ku",
        rimeGroup: rimeGroups.u,
        onsetGroups: onsetGroups.k,
    },
    {
        id: 9,
        term: "け",
        definition: "ke",
        rimeGroup: rimeGroups.e,
        onsetGroups: onsetGroups.k,
    },
    {
        id: 10,
        term: "こ",
        definition: "ko",
        rimeGroup: rimeGroups.o,
        onsetGroups: onsetGroups.k,
    },
    {
        id: 11,
        term: "さ",
        definition: "sa",
        rimeGroup: rimeGroups.a,
        onsetGroups: onsetGroups.s,
    },
    {
        id: 12,
        term: "し",
        definition: "shi",
        rimeGroup: rimeGroups.hi,
        onsetGroups: onsetGroups.s,
    },
    {
        id: 13,
        term: "す",
        definition: "su",
        rimeGroup: rimeGroups.u,
        onsetGroups: onsetGroups.s,
    },
    {
        id: 14,
        term: "せ",
        definition: "se",
        rimeGroup: rimeGroups.e,
        onsetGroups: onsetGroups.s,
    },
    {
        id: 15,
        term: "そ",
        definition: "so",
        rimeGroup: rimeGroups.o,
        onsetGroups: onsetGroups.s,
    },
    {
        id: 16,
        term: "た",
        definition: "ta",
        rimeGroup: rimeGroups.a,
        onsetGroups: onsetGroups.t,
    },
    {
        id: 17,
        term: "ち",
        definition: "chi",
        rimeGroup: rimeGroups.hi,
        onsetGroups: onsetGroups.t,
    },
    {
        id: 18,
        term: "つ",
        definition: "tsu",
        rimeGroup: rimeGroups.su,
        onsetGroups: onsetGroups.t,
    },
    {
        id: 19,
        term: "て",
        definition: "te",
        rimeGroup: rimeGroups.e,
        onsetGroups: onsetGroups.t,
    },
    {
        id: 20,
        term: "と",
        definition: "to",
        rimeGroup: rimeGroups.o,
        onsetGroups: onsetGroups.t,
    },
    {
        id: 21,
        term: "な",
        definition: "na",
        rimeGroup: rimeGroups.a,
        onsetGroups: onsetGroups.n,
    },
    {
        id: 22,
        term: "に",
        definition: "ni",
        rimeGroup: rimeGroups.i,
        onsetGroups: onsetGroups.n,
    },
    {
        id: 23,
        term: "ぬ",
        definition: "nu",
        rimeGroup: rimeGroups.u,
        onsetGroups: onsetGroups.n,
    },
    {
        id: 24,
        term: "ね",
        definition: "ne",
        rimeGroup: rimeGroups.e,
        onsetGroups: onsetGroups.n,
    },
    {
        id: 25,
        term: "の",
        definition: "no",
        rimeGroup: rimeGroups.o,
        onsetGroups: onsetGroups.n,
    },
    {
        id: 26,
        term: "は",
        definition: "ha",
        rimeGroup: rimeGroups.a,
        onsetGroups: onsetGroups.h,
    },
    {
        id: 27,
        term: "ひ",
        definition: "hi",
        rimeGroup: rimeGroups.i,
        onsetGroups: onsetGroups.h,
    },
    {
        id: 28,
        term: "ふ",
        definition: "fu",
        rimeGroup: rimeGroups.u,
        onsetGroups: onsetGroups.h,
    },
    {
        id: 29,
        term: "へ",
        definition: "he",
        rimeGroup: rimeGroups.e,
        onsetGroups: onsetGroups.h,
    },
    {
        id: 30,
        term: "ほ",
        definition: "ho",
        rimeGroup: rimeGroups.o,
        onsetGroups: onsetGroups.h,
    },
    {
        id: 31,
        term: "ま",
        definition: "ma",
        rimeGroup: rimeGroups.a,
        onsetGroups: onsetGroups.m,
    },
    {
        id: 32,
        term: "み",
        definition: "mi",
        rimeGroup: rimeGroups.i,
        onsetGroups: onsetGroups.m,
    },
    {
        id: 33,
        term: "む",
        definition: "mu",
        rimeGroup: rimeGroups.u,
        onsetGroups: onsetGroups.m,
    },
    {
        id: 34,
        term: "め",
        definition: "me",
        rimeGroup: rimeGroups.e,
        onsetGroups: onsetGroups.m,
    },
    {
        id: 35,
        term: "も",
        definition: "mo",
        rimeGroup: rimeGroups.o,
        onsetGroups: onsetGroups.m,
    },
    {
        id: 36,
        term: "や",
        definition: "ya",
        rimeGroup: rimeGroups.a,
        onsetGroups: onsetGroups.y,
    },
    {
        id: 37,
        term: "ゆ",
        definition: "yu",
        rimeGroup: rimeGroups.u,
        onsetGroups: onsetGroups.y,
    },
    {
        id: 38,
        term: "よ",
        definition: "yo",
        rimeGroup: rimeGroups.o,
        onsetGroups: onsetGroups.y,
    },
    {
        id: 39,
        term: "ら",
        definition: "ra",
        rimeGroup: rimeGroups.a,
        onsetGroups: onsetGroups.r,
    },
    {
        id: 40,
        term: "り",
        definition: "ri",
        rimeGroup: rimeGroups.i,
        onsetGroups: onsetGroups.r,
    },
    {
        id: 41,
        term: "る",
        definition: "ru",
        rimeGroup: rimeGroups.u,
        onsetGroups: onsetGroups.r,
    },
    {
        id: 42,
        term: "れ",
        definition: "re",
        rimeGroup: rimeGroups.e,
        onsetGroups: onsetGroups.r,
    },
    {
        id: 43,
        term: "ろ",
        definition: "ro",
        rimeGroup: rimeGroups.o,
        onsetGroups: onsetGroups.r,
    },
    {
        id: 44,
        term: "わ",
        definition: "wa",
        rimeGroup: rimeGroups.a,
        onsetGroups: onsetGroups.w,
    },
    {
        id: 45,
        term: "を",
        definition: "wo",
        rimeGroup: rimeGroups.o,
        onsetGroups: onsetGroups.w,
    },
    {
        id: 46,
        term: "ん",
        definition: "n",
        rimeGroup: rimeGroups.n,
        onsetGroups: onsetGroups.n,
    },
    {
        id: 47,
        term: "が",
        definition: "ga",
        rimeGroup: rimeGroups.a,
        onsetGroups: onsetGroups.g,
    },
    {
        id: 48,
        term: "ぎ",
        definition: "gi",
        rimeGroup: rimeGroups.i,
        onsetGroups: onsetGroups.g,
    },
    {
        id: 49,
        term: "ぐ",
        definition: "gu",
        rimeGroup: rimeGroups.u,
        onsetGroups: onsetGroups.g,
    },
    {
        id: 50,
        term: "げ",
        definition: "ge",
        rimeGroup: rimeGroups.e,
        onsetGroups: onsetGroups.g,
    },
    {
        id: 51,
        term: "ご",
        definition: "go",
        rimeGroup: rimeGroups.o,
        onsetGroups: onsetGroups.g,
    },
    {
        id: 52,
        term: "ざ",
        definition: "za",
        rimeGroup: rimeGroups.a,
        onsetGroups: onsetGroups.z,
    },
    {
        id: 53,
        term: "じ",
        definition: "ji",
        rimeGroup: rimeGroups.i,
        onsetGroups: onsetGroups.j,
    },
    {
        id: 54,
        term: "ず",
        definition: "zu",
        rimeGroup: rimeGroups.u,
        onsetGroups: onsetGroups.z,
    },
    {
        id: 55,
        term: "ぜ",
        definition: "ze",
        rimeGroup: rimeGroups.e,
        onsetGroups: onsetGroups.z,
    },
    {
        id: 56,
        term: "ぞ",
        definition: "zo",
        rimeGroup: rimeGroups.o,
        onsetGroups: onsetGroups.z,
    },
    {
        id: 57,
        term: "だ",
        definition: "da",
        rimeGroup: rimeGroups.a,
        onsetGroups: onsetGroups.d,
    },
    {
        id: 58,
        term: "ぢ",
        definition: "ji",
        rimeGroup: rimeGroups.i,
        onsetGroups: onsetGroups.j,
    },
    {
        id: 59,
        term: "づ",
        definition: "zu",
        rimeGroup: rimeGroups.u,
        onsetGroups: onsetGroups.z,
    },
    {
        id: 60,
        term: "で",
        definition: "de",
        rimeGroup: rimeGroups.e,
        onsetGroups: onsetGroups.d,
    },
    {
        id: 61,
        term: "ど",
        definition: "do",
        rimeGroup: rimeGroups.o,
        onsetGroups: onsetGroups.d,
    },
    {
        id: 62,
        term: "ば",
        definition: "ba",
        rimeGroup: rimeGroups.a,
        onsetGroups: onsetGroups.b,
    },
    {
        id: 63,
        term: "び",
        definition: "bi",
        rimeGroup: rimeGroups.i,
        onsetGroups: onsetGroups.b,
    },
    {
        id: 64,
        term: "ぶ",
        definition: "bu",
        rimeGroup: rimeGroups.u,
        onsetGroups: onsetGroups.b,
    },
    {
        id: 65,
        term: "べ",
        definition: "be",
        rimeGroup: rimeGroups.e,
        onsetGroups: onsetGroups.b,
    },
    {
        id: 66,
        term: "ぼ",
        definition: "bo",
        rimeGroup: rimeGroups.o,
        onsetGroups: onsetGroups.b,
    },
    {
        id: 67,
        term: "ぱ",
        definition: "pa",
        rimeGroup: rimeGroups.a,
        onsetGroups: onsetGroups.p,
    },
    {
        id: 68,
        term: "ぴ",
        definition: "pi",
        rimeGroup: rimeGroups.i,
        onsetGroups: onsetGroups.p,
    },
    {
        id: 69,
        term: "ぷ",
        definition: "pu",
        rimeGroup: rimeGroups.u,
        onsetGroups: onsetGroups.p,
    },
    {
        id: 70,
        term: "ぺ",
        definition: "pe",
        rimeGroup: rimeGroups.e,
        onsetGroups: onsetGroups.p,
    },
    {
        id: 71,
        term: "ぽ",
        definition: "po",
        rimeGroup: rimeGroups.o,
        onsetGroups: onsetGroups.p,
    },
    {
        id: 72,
        term: "きゃ",
        definition: "kya",
        rimeGroup: rimeGroups.ya,
        onsetGroups: onsetGroups.k,
    },
    {
        id: 73,
        term: "きゅ",
        definition: "kyu",
        rimeGroup: rimeGroups.yu,
        onsetGroups: onsetGroups.k,
    },
    {
        id: 74,
        term: "きょ",
        definition: "kyo",
        rimeGroup: rimeGroups.yo,
        onsetGroups: onsetGroups.k,
    },
    {
        id: 75,
        term: "ぎゃ",
        definition: "gya",
        rimeGroup: rimeGroups.ya,
        onsetGroups: onsetGroups.k,
    },
    {
        id: 76,
        term: "ぎゅ",
        definition: "gyu",
        rimeGroup: rimeGroups.yu,
        onsetGroups: onsetGroups.g,
    },
    {
        id: 77,
        term: "ぎょ",
        definition: "gyo",
        rimeGroup: rimeGroups.yo,
        onsetGroups: onsetGroups.g,
    },
    {
        id: 78,
        term: "しゃ",
        definition: "sha",
        rimeGroup: rimeGroups.ha,
        onsetGroups: onsetGroups.s,
    },
    {
        id: 79,
        term: "しゅ",
        definition: "shu",
        rimeGroup: rimeGroups.hu,
        onsetGroups: onsetGroups.s,
    },
    {
        id: 80,
        term: "しょ",
        definition: "sho",
        rimeGroup: rimeGroups.ho,
        onsetGroups: onsetGroups.s,
    },
    {
        id: 81,
        term: "じゃ",
        definition: "ja",
        rimeGroup: rimeGroups.a,
        onsetGroups: onsetGroups.j,
    },
    {
        id: 82,
        term: "じゅ",
        definition: "ju",
        rimeGroup: rimeGroups.u,
        onsetGroups: onsetGroups.j,
    },
    {
        id: 83,
        term: "じょ",
        definition: "jo",
        rimeGroup: rimeGroups.o,
        onsetGroups: onsetGroups.j,
    },
    {
        id: 84,
        term: "ちゃ",
        definition: "cha",
        rimeGroup: rimeGroups.ha,
        onsetGroups: onsetGroups.c,
    },
    {
        id: 85,
        term: "ちゅ",
        definition: "chu",
        rimeGroup: rimeGroups.hu,
        onsetGroups: onsetGroups.c,
    },
    {
        id: 86,
        term: "ちょ",
        definition: "cho",
        rimeGroup: rimeGroups.ho,
        onsetGroups: onsetGroups.c,
    },
    {
        id: 87,
        term: "にゃ",
        definition: "nya",
        rimeGroup: rimeGroups.ya,
        onsetGroups: onsetGroups.n,
    },
    {
        id: 88,
        term: "にゅ",
        definition: "nyu",
        rimeGroup: rimeGroups.yu,
        onsetGroups: onsetGroups.n,
    },
    {
        id: 89,
        term: "にょ",
        definition: "nyo",
        rimeGroup: rimeGroups.yo,
        onsetGroups: onsetGroups.n,
    },
    {
        id: 90,
        term: "ひゃ",
        definition: "hya",
        rimeGroup: rimeGroups.ya,
        onsetGroups: onsetGroups.h,
    },
    {
        id: 91,
        term: "ひゅ",
        definition: "hyu",
        rimeGroup: rimeGroups.yu,
        onsetGroups: onsetGroups.h,
    },
    {
        id: 92,
        term: "ひょ",
        definition: "hyo",
        rimeGroup: rimeGroups.yo,
        onsetGroups: onsetGroups.h,
    },
    {
        id: 93,
        term: "びゃ",
        definition: "bya",
        rimeGroup: rimeGroups.ya,
        onsetGroups: onsetGroups.b,
    },
    {
        id: 94,
        term: "びゅ",
        definition: "byu",
        rimeGroup: rimeGroups.yu,
        onsetGroup: onsetGroups.b,
    },
    {
        id: 95,
        term: "びょ",
        definition: "byo",
        rimeGroup: rimeGroups.yo,
        onsetGroup: onsetGroups.b,
    },
    {
        id: 96,
        term: "ぴゃ",
        definition: "pya",
        rimeGroup: rimeGroups.ya,
        onsetGroup: onsetGroups.p,
    },
    {
        id: 97,
        term: "ぴゅ",
        definition: "pyu",
        rimeGroup: rimeGroups.yu,
        onsetGroup: onsetGroups.p,
    },
    {
        id: 98,
        term: "ぴょ",
        definition: "pyo",
        rimeGroup: rimeGroups.yo,
        onsetGroup: onsetGroups.p,
    },
    {
        id: 99,
        term: "みゃ",
        definition: "mya",
        rimeGroup: rimeGroups.ya,
        onsetGroup: onsetGroups.m,
    },
    {
        id: 100,
        term: "みゅ",
        definition: "myu",
        rimeGroup: rimeGroups.yu,
        onsetGroup: onsetGroups.m,
    },
    {
        id: 101,
        term: "みょ",
        definition: "myo",
        rimeGroup: rimeGroups.yo,
        onsetGroup: onsetGroups.m,
    },
    {
        id: 102,
        term: "りゃ",
        definition: "rya",
        rimeGroup: rimeGroups.ya,
        onsetGroup: onsetGroups.r,
    },
    {
        id: 103,
        term: "りゅ",
        definition: "ryu",
        rimeGroup: rimeGroups.yu,
        onsetGroup: onsetGroups.r,
    },
    {
        id: 104,
        term: "りょ",
        definition: "ryo",
        rimeGroup: rimeGroups.yo,
        onsetGroup: onsetGroups.r,
    },
]);

export const katakana = Object.freeze([
    {
        id: 105,
        term: "ア",
        definition: "a",
        rimeGroup: rimeGroups.a,
        onsetGroup: onsetGroups.vowels,
    },
    {
        id: 106,
        term: "イ",
        definition: "i",
        rimeGroup: rimeGroups.i,
        onsetGroup: onsetGroups.vowels,
    },
    {
        id: 107,
        term: "ウ",
        definition: "u",
        rimeGroup: rimeGroups.u,
        onsetGroup: onsetGroups.vowels,
    },
    {
        id: 108,
        term: "エ",
        definition: "e",
        rimeGroup: rimeGroups.e,
        onsetGroup: onsetGroups.vowels,
    },
    {
        id: 109,
        term: "オ",
        definition: "o",
        rimeGroup: rimeGroups.o,
        onsetGroup: onsetGroups.vowels,
    },
    {
        id: 110,
        term: "カ",
        definition: "ka",
        rimeGroup: rimeGroups.a,
        onsetGroup: onsetGroups.k,
    },
    {
        id: 111,
        term: "キ",
        definition: "ki",
        rimeGroup: rimeGroups.i,
        onsetGroup: onsetGroups.k,
    },
    {
        id: 112,
        term: "ク",
        definition: "ku",
        rimeGroup: rimeGroups.u,
        onsetGroup: onsetGroups.k,
    },
    {
        id: 113,
        term: "ケ",
        definition: "ke",
        rimeGroup: rimeGroups.e,
        onsetGroup: onsetGroups.k,
    },
    {
        id: 114,
        term: "コ",
        definition: "ko",
        rimeGroup: rimeGroups.o,
        onsetGroup: onsetGroups.k,
    },
    {
        id: 115,
        term: "サ",
        definition: "sa",
        rimeGroup: rimeGroups.a,
        onsetGroup: onsetGroups.s,
    },
    {
        id: 116,
        term: "シ",
        definition: "shi",
        rimeGroup: rimeGroups.hi,
        onsetGroup: onsetGroups.s,
    },
    {
        id: 117,
        term: "ス",
        definition: "su",
        rimeGroup: rimeGroups.u,
        onsetGroup: onsetGroups.s,
    },
    {
        id: 118,
        term: "セ",
        definition: "se",
        rimeGroup: rimeGroups.e,
        onsetGroup: onsetGroups.s,
    },
    {
        id: 119,
        term: "ソ",
        definition: "so",
        rimeGroup: rimeGroups.o,
        onsetGroup: onsetGroups.s,
    },
    {
        id: 120,
        term: "タ",
        definition: "ta",
        rimeGroup: rimeGroups.a,
        onsetGroup: onsetGroups.t,
    },
    {
        id: 121,
        term: "チ",
        definition: "chi",
        rimeGroup: rimeGroups.hi,
        onsetGroup: onsetGroups.t,
    },
    {
        id: 122,
        term: "ツ",
        definition: "tsu",
        rimeGroup: rimeGroups.su,
        onsetGroup: onsetGroups.t,
    },
    {
        id: 123,
        term: "テ",
        definition: "te",
        rimeGroup: rimeGroups.e,
        onsetGroup: onsetGroups.t,
    },
    {
        id: 124,
        term: "ト",
        definition: "to",
        rimeGroup: rimeGroups.o,
        onsetGroup: onsetGroups.t,
    },
    {
        id: 125,
        term: "ナ",
        definition: "na",
        rimeGroup: rimeGroups.a,
        onsetGroup: onsetGroups.n,
    },
    {
        id: 126,
        term: "ニ",
        definition: "ni",
        rimeGroup: rimeGroups.i,
        onsetGroup: onsetGroups.n,
    },
    {
        id: 127,
        term: "ヌ",
        definition: "nu",
        rimeGroup: rimeGroups.u,
        onsetGroup: onsetGroups.n,
    },
    {
        id: 128,
        term: "ネ",
        definition: "ne",
        rimeGroup: rimeGroups.e,
        onsetGroup: onsetGroups.n,
    },
    {
        id: 129,
        term: "ノ",
        definition: "no",
        rimeGroup: rimeGroups.o,
        onsetGroup: onsetGroups.n,
    },
    {
        id: 130,
        term: "ハ",
        definition: "ha",
        rimeGroup: rimeGroups.a,
        onsetGroup: onsetGroups.h,
    },
    {
        id: 131,
        term: "ヒ",
        definition: "hi",
        rimeGroup: rimeGroups.i,
        onsetGroup: onsetGroups.h,
    },
    {
        id: 132,
        term: "フ",
        definition: "fu",
        rimeGroup: rimeGroups.u,
        onsetGroup: onsetGroups.h,
    },
    {
        id: 133,
        term: "ヘ",
        definition: "he",
        rimeGroup: rimeGroups.e,
        onsetGroup: onsetGroups.h,
    },
    {
        id: 134,
        term: "ホ",
        definition: "ho",
        rimeGroup: rimeGroups.o,
        onsetGroup: onsetGroups.h,
    },
    {
        id: 135,
        term: "マ",
        definition: "ma",
        rimeGroup: rimeGroups.a,
        onsetGroup: onsetGroups.m,
    },
    {
        id: 136,
        term: "ミ",
        definition: "mi",
        rimeGroup: rimeGroups.i,
        onsetGroup: onsetGroups.m,
    },
    {
        id: 137,
        term: "ム",
        definition: "mu",
        rimeGroup: rimeGroups.u,
        onsetGroup: onsetGroups.m,
    },
    {
        id: 138,
        term: "メ",
        definition: "me",
        rimeGroup: rimeGroups.e,
        onsetGroup: onsetGroups.m,
    },
    {
        id: 139,
        term: "モ",
        definition: "mo",
        rimeGroup: rimeGroups.o,
        onsetGroup: onsetGroups.m,
    },
    {
        id: 140,
        term: "ヤ",
        definition: "ya",
        rimeGroup: rimeGroups.a,
        onsetGroup: onsetGroups.y,
    },
    {
        id: 141,
        term: "ユ",
        definition: "yu",
        rimeGroup: rimeGroups.u,
        onsetGroup: onsetGroups.y,
    },
    {
        id: 142,
        term: "ヨ",
        definition: "yo",
        rimeGroup: rimeGroups.o,
        onsetGroup: onsetGroups.y,
    },
    {
        id: 143,
        term: "ラ",
        definition: "ra",
        rimeGroup: rimeGroups.a,
        onsetGroup: onsetGroups.r,
    },
    {
        id: 144,
        term: "リ",
        definition: "ri",
        rimeGroup: rimeGroups.i,
        onsetGroup: onsetGroups.r,
    },
    {
        id: 145,
        term: "ル",
        definition: "ru",
        rimeGroup: rimeGroups.u,
        onsetGroup: onsetGroups.r,
    },
    {
        id: 146,
        term: "レ",
        definition: "re",
        rimeGroup: rimeGroups.e,
        onsetGroup: onsetGroups.r,
    },
    {
        id: 147,
        term: "ロ",
        definition: "ro",
        rimeGroup: rimeGroups.o,
        onsetGroup: onsetGroups.r,
    },
    {
        id: 148,
        term: "ワ",
        definition: "wa",
        rimeGroup: rimeGroups.a,
        onsetGroup: onsetGroups.w,
    },
    {
        id: 149,
        term: "ヲ",
        definition: "wo",
        rimeGroup: rimeGroups.o,
        onsetGroup: onsetGroups.w,
    },
    {
        id: 150,
        term: "ン",
        definition: "n",
        rimeGroup: rimeGroups.n,
        onsetGroup: onsetGroups.n,
    },
    {
        id: 151,
        term: "ガ",
        definition: "ga",
        rimeGroup: rimeGroups.a,
        onsetGroup: onsetGroups.g,
    },
    {
        id: 152,
        term: "ギ",
        definition: "gi",
        rimeGroup: rimeGroups.i,
        onsetGroup: onsetGroups.g,
    },
    {
        id: 153,
        term: "グ",
        definition: "gu",
        rimeGroup: rimeGroups.u,
        onsetGroup: onsetGroups.g,
    },
    {
        id: 154,
        term: "ゲ",
        definition: "ge",
        rimeGroup: rimeGroups.e,
        onsetGroup: onsetGroups.g,
    },
    {
        id: 155,
        term: "ゴ",
        definition: "go",
        rimeGroup: rimeGroups.o,
        onsetGroup: onsetGroups.g,
    },
    {
        id: 156,
        term: "ザ",
        definition: "za",
        rimeGroup: rimeGroups.a,
        onsetGroup: onsetGroups.z,
    },
    {
        id: 157,
        term: "ジ",
        definition: "ji",
        rimeGroup: rimeGroups.i,
        onsetGroup: onsetGroups.j,
    },
    {
        id: 158,
        term: "ズ",
        definition: "zu",
        rimeGroup: rimeGroups.u,
        onsetGroup: onsetGroups.z,
    },
    {
        id: 159,
        term: "ゼ",
        definition: "ze",
        rimeGroup: rimeGroups.e,
        onsetGroup: onsetGroups.z,
    },
    {
        id: 160,
        term: "ゾ",
        definition: "zo",
        rimeGroup: rimeGroups.o,
        onsetGroup: onsetGroups.z,
    },
    {
        id: 161,
        term: "ダ",
        definition: "da",
        rimeGroup: rimeGroups.a,
        onsetGroup: onsetGroups.d,
    },
    {
        id: 162,
        term: "ヂ",
        definition: "ji",
        rimeGroup: rimeGroups.i,
        onsetGroup: onsetGroups.j,
    },
    {
        id: 163,
        term: "ヅ",
        definition: "zu",
        rimeGroup: rimeGroups.u,
        onsetGroup: onsetGroups.z,
    },
    {
        id: 164,
        term: "デ",
        definition: "de",
        rimeGroup: rimeGroups.e,
        onsetGroup: onsetGroups.d,
    },
    {
        id: 165,
        term: "ド",
        definition: "do",
        rimeGroup: rimeGroups.o,
        onsetGroup: onsetGroups.d,
    },
    {
        id: 166,
        term: "バ",
        definition: "ba",
        rimeGroup: rimeGroups.a,
        onsetGroup: onsetGroups.b,
    },
    {
        id: 167,
        term: "ビ",
        definition: "bi",
        rimeGroup: rimeGroups.i,
        onsetGroup: onsetGroups.b,
    },
    {
        id: 168,
        term: "ブ",
        definition: "bu",
        rimeGroup: rimeGroups.u,
        onsetGroup: onsetGroups.b,
    },
    {
        id: 169,
        term: "ベ",
        definition: "be",
        rimeGroup: rimeGroups.e,
        onsetGroup: onsetGroups.b,
    },
    {
        id: 170,
        term: "ボ",
        definition: "bo",
        rimeGroup: rimeGroups.o,
        onsetGroup: onsetGroups.b,
    },
    {
        id: 171,
        term: "パ",
        definition: "pa",
        rimeGroup: rimeGroups.a,
        onsetGroup: onsetGroups.p,
    },
    {
        id: 172,
        term: "ピ",
        definition: "pi",
        rimeGroup: rimeGroups.i,
        onsetGroup: onsetGroups.p,
    },
    {
        id: 173,
        term: "プ",
        definition: "pu",
        rimeGroup: rimeGroups.u,
        onsetGroup: onsetGroups.p,
    },
    {
        id: 174,
        term: "ペ",
        definition: "pe",
        rimeGroup: rimeGroups.e,
        onsetGroup: onsetGroups.p,
    },
    {
        id: 175,
        term: "ポ",
        definition: "po",
        rimeGroup: rimeGroups.o,
        onsetGroup: onsetGroups.p,
    },
    {
        id: 176,
        term: "キャ",
        definition: "kya",
        rimeGroup: rimeGroups.ya,
        onsetGroup: onsetGroups.k,
    },
    {
        id: 177,
        term: "キュ",
        definition: "kyu",
        rimeGroup: rimeGroups.yu,
        onsetGroup: onsetGroups.k,
    },
    {
        id: 178,
        term: "キョ",
        definition: "kyo",
        rimeGroup: rimeGroups.yo,
        onsetGroup: onsetGroups.k,
    },
    {
        id: 179,
        term: "ギャ",
        definition: "gya",
        rimeGroup: rimeGroups.ya,
        onsetGroup: onsetGroups.g,
    },
    {
        id: 180,
        term: "ギュ",
        definition: "gyu",
        rimeGroup: rimeGroups.yu,
        onsetGroup: onsetGroups.g,
    },
    {
        id: 181,
        term: "ギョ",
        definition: "gyo",
        rimeGroup: rimeGroups.yo,
        onsetGroup: onsetGroups.g,
    },
    {
        id: 182,
        term: "シャ",
        definition: "sha",
        rimeGroup: rimeGroups.ha,
        onsetGroup: onsetGroups.s,
    },
    {
        id: 183,
        term: "シュ",
        definition: "shu",
        rimeGroup: rimeGroups.hu,
        onsetGroup: onsetGroups.s,
    },
    {
        id: 184,
        term: "ショ",
        definition: "sho",
        rimeGroup: rimeGroups.ho,
        onsetGroup: onsetGroups.s,
    },
    {
        id: 185,
        term: "ジャ",
        definition: "ja",
        rimeGroup: rimeGroups.a,
        onsetGroup: onsetGroups.j,
    },
    {
        id: 186,
        term: "ジュ",
        definition: "ju",
        rimeGroup: rimeGroups.u,
        onsetGroup: onsetGroups.j,
    },
    {
        id: 187,
        term: "ジョ",
        definition: "jo",
        rimeGroup: rimeGroups.o,
        onsetGroup: onsetGroups.j,
    },
    {
        id: 188,
        term: "チャ",
        definition: "cha",
        rimeGroup: rimeGroups.ha,
        onsetGroup: onsetGroups.c,
    },
    {
        id: 189,
        term: "チュ",
        definition: "chu",
        rimeGroup: rimeGroups.hu,
        onsetGroup: onsetGroups.c,
    },
    {
        id: 190,
        term: "チョ",
        definition: "cho",
        rimeGroup: rimeGroups.ho,
        onsetGroup: onsetGroups.c,
    },
    {
        id: 191,
        term: "ニャ",
        definition: "nya",
        rimeGroup: rimeGroups.ya,
        onsetGroup: onsetGroups.n,
    },
    {
        id: 192,
        term: "ニュ",
        definition: "nyu",
        rimeGroup: rimeGroups.yu,
        onsetGroup: onsetGroups.n,
    },
    {
        id: 193,
        term: "ニョ",
        definition: "nyo",
        rimeGroup: rimeGroups.yo,
        onsetGroup: onsetGroups.n,
    },
    {
        id: 194,
        term: "ヒャ",
        definition: "hya",
        rimeGroup: rimeGroups.ya,
        onsetGroup: onsetGroups.h,
    },
    {
        id: 195,
        term: "ヒュ",
        definition: "hyu",
        rimeGroup: rimeGroups.yu,
        onsetGroup: onsetGroups.h,
    },
    {
        id: 196,
        term: "ヒョ",
        definition: "hyo",
        rimeGroup: rimeGroups.yo,
        onsetGroup: onsetGroups.h,
    },
    {
        id: 197,
        term: "ビャ",
        definition: "bya",
        rimeGroup: rimeGroups.ya,
        onsetGroup: onsetGroups.b,
    },
    {
        id: 198,
        term: "ビュ",
        definition: "byu",
        rimeGroup: rimeGroups.yu,
        onsetGroup: onsetGroups.b,
    },
    {
        id: 199,
        term: "ビョ",
        definition: "byo",
        rimeGroup: rimeGroups.yo,
        onsetGroup: onsetGroups.b,
    },
    {
        id: 200,
        term: "ピャ",
        definition: "pya",
        rimeGroup: rimeGroups.ya,
        onsetGroup: onsetGroups.p,
    },
    {
        id: 201,
        term: "ピュ",
        definition: "pyu",
        rimeGroup: rimeGroups.yu,
        onsetGroup: onsetGroups.p,
    },
    {
        id: 202,
        term: "ピョ",
        definition: "pyo",
        rimeGroup: rimeGroups.yo,
        onsetGroup: onsetGroups.p,
    },
    {
        id: 203,
        term: "ミャ",
        definition: "mya",
        rimeGroup: rimeGroups.ya,
        onsetGroup: onsetGroups.m,
    },
    {
        id: 204,
        term: "ミュ",
        definition: "myu",
        rimeGroup: rimeGroups.yu,
        onsetGroup: onsetGroups.m,
    },
    {
        id: 205,
        term: "ミョ",
        definition: "myo",
        rimeGroup: rimeGroups.yo,
        onsetGroup: onsetGroups.m,
    },
    {
        id: 206,
        term: "リャ",
        definition: "rya",
        rimeGroup: rimeGroups.ya,
        onsetGroup: onsetGroups.r,
    },
    {
        id: 207,
        term: "リュ",
        definition: "ryu",
        rimeGroup: rimeGroups.yu,
        onsetGroup: onsetGroups.r,
    },
    {
        id: 208,
        term: "リョ",
        definition: "ryo",
        rimeGroup: rimeGroups.yo,
        onsetGroup: onsetGroups.r,
    },
]);

export const hiraganaTerms = Object.freeze(hiragana.map((x) => x.term));
export const katakanaTerms = Object.freeze(katakana.map((x) => x.term));
export const totalsrimeGroup = Object.freeze(
    Object.entries(Object.groupBy(hiragana, (x) => x.rimeGroup)).reduce(
        (x, y) => ({ ...x, [y[0]]: y[1].length }),
        {},
    ),
);

export const methodsKeys = Object.freeze({
    typing: "typing",
    listening: "listening",
    drawing: "drawing",
});

export const scores = Object.freeze({
    [methodsKeys.typing]: Object.freeze({ max: 100 }),
    [methodsKeys.listening]: Object.freeze({ max: 50 }),
    [methodsKeys.drawing]: Object.freeze({ max: 200, min: 50 }),
});

export const databasesTypes = Object.freeze({
    hiragana: "hiragana",
    katakana: "katakana",
    kanas: "kanas",
    words: "words",
});

export const databasesData = Object.freeze({
    [databasesTypes.hiragana]: hiragana,
    [databasesTypes.katakana]: katakana,
    [databasesTypes.kanas]: Object.freeze([...hiragana, ...katakana]),
    [databasesTypes.words]: [],
});

export const defaults = databasesData.kanas.reduce(
    (a, b) => ({
        ...a,
        [b.term]: Object.values(methodsKeys).reduce(
            (x, y) => ({ ...x, [y]: 0 }),
            {},
        ),
    }),
    {},
);

export const japanese = "ja";
